### ISSUE TITLE
Github.io Page - basic setup with i18n functionality

### ISSUE THREAD

**Issue by britthurley** [SSC-CIO-DigitalTaskForce/SSC-CIO-DigitalTaskForce.github.io#1]
I'd like to set up a Github.io page to share our work in the open. We can go live before perfection, but we should aim for Accessibility and Bilingualism as much as possible.

The GCDevOpsLeage page can be used as an example (created by Guillaume Charest). Deepl was used for french translations.

https://gcdevops.github.io/

**Comment by patheard** [comment]
Following [this guide](https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll) to setup a local Jekyll environment for dev.

Had to install Ruby from the [7z archive](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.6.4-1/rubyinstaller-2.6.4-1-x64.7z) and set the PATH manually, but so far, it appears to be working.

**Comment by patheard** [comment]
Looking at Jekyll themes, and I think this will be a good base we can build on:
https://github.com/rohanchandra/type-theme

**Comment by patheard** [comment]
I spoke too soon.  I've been fighting with a locked down laptop all afternoon and still don't have a local dev environment setup 👎

**Comment by patheard** [comment]
As expected, in less than 5 minutes on my computer, everything's setup and working just fine 🙄

**Comment by patheard** [comment]
Alrighty, first version deployed to gh-pages: 

https://ssc-cio-digitaltaskforce.github.io/home/

Let me know what you think!   The content is pretty much a copy/pasta of your deck.

Things I still want to do:

- play with the fonts/spacing. 
- fix the landing page style
- add a Contact page
- add a build process
- beef up the README.md with info on the features and how to manage the site.

One note - I had to change the repo name so it would work as an [organization gh-pages site](https://help.github.com/en/articles/user-organization-and-project-pages#user-and-organization-pages-sites).
